
const constants = {
    USERNAME_EMPTY: "USERNAME_EMPTY",
    EMAIL_EMPTY: "EMAIL_EMPTY",
    ID_EMPTY: "ID_EMPTY",
    URL_EMPTY: "URL_EMPTY",

    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    USER_DOES_NOT_EXISTS: "USER_DOES_NOT_EXISTS",
    REPO_DOES_NOT_EXISTS: "REPO_DOES_NOT_EXISTS",
    REPO_ALREADY_EXISTS: "REPO_ALREADY_EXISTS",

    WRITE_FILE_ERROR: 'WRITE_FILE_ERROR',
    PATH_INVAID: 'PATH_INVAID',
    DATA_INVALID: 'DATA_INVALID',

    EMPTY_STRING: 'EMPTY_STRING',
    PARSING_ERR: 'PARSING_ERR',
    COMMAND_ERR: 'COMMAND_ERR',
    DONT_HAVE_PERMISSION: 'DONT_HAVE_PERMISSION',
    NOT_FOUND: 'NOT_FOUND: ',
    OK: 'OK',

    INVALID: 'INVALID',
    FILE_ALREADY_EXISTS: 'FILE_ALREADY_EXISTS',
    GIT_FILE_NOT_FOUND: 'GIT_FILE_NOT_FOUND',

    USER_DEFAULT_EMPTY: 'USER_DEFAULT_EMPTY'
}

module.exports = constants;
