
const constants = {
    USERNAME_EMPTY: "USERNAME_EMPTY",
    EMAIL_EMPTY: "EMAIL_EMPTY",

    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    USER_DOES_NOT_EXISTS: "USER_DOES_NOT_EXISTS",

    WRITE_FILE_ERROR: 'WRITE_FILE_ERROR',
    PATH_INVAID: 'PATH_INVAID',
    DATA_INVALID: 'DATA_INVALID',

    EMPTY_STRING: 'EMPTY_STRING',
    PARSING_ERR: 'PARSING_ERR',
    COMMAND_ERR: 'COMMAND_ERR',
    DONT_HAVE_PERMISSION: 'DONT_HAVE_PERMISSION',
    NOT_FOUND: 'NOT_FOUND: ',
    OK: 'OK',
    INVALID: 'INVALID'
}

module.exports = constants;

